[package]
name = "mypipe"
version = "1.0.0"
authors = ["Florian BERGERON <bergeron.florian@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
